kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  {{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{ end }}
data:
  {{- range $key, $val := .Values.configs }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}